package org.interledger.connector;

import org.interledger.connector.accounts.AccountSettings;
import org.interledger.connector.events.PacketEventPublisher;
import org.interledger.connector.settings.ConnectorSettings;
import org.interledger.core.InterledgerErrorCode;
import org.interledger.core.InterledgerPreparePacket;
import org.interledger.core.InterledgerProtocolException;
import org.interledger.core.InterledgerRejectPacket;
import org.interledger.link.LinkId;
import org.interledger.link.PacketRejector;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Objects;
import java.util.function.Supplier;

/**
 * A centralized place to handle all exceptions generated by this Connector.
 */
public class ConnectorExceptionHandler {

  private final Logger logger = LoggerFactory.getLogger(this.getClass());

  private final Supplier<ConnectorSettings> connectorSettingsSupplier;
  private final PacketRejector packetRejector;
  private final PacketEventPublisher packetEventPublisher;

  public ConnectorExceptionHandler(
    final Supplier<ConnectorSettings> connectorSettingsSupplier, final PacketRejector packetRejector,
    PacketEventPublisher packetEventPublisher) {
    this.connectorSettingsSupplier = connectorSettingsSupplier;
    this.packetRejector = packetRejector;
    this.packetEventPublisher = packetEventPublisher;
  }

  public InterledgerRejectPacket handleException(
    final AccountSettings sourceAccountSettings, final InterledgerPreparePacket preparePacket, final Exception e
  ) {
    Objects.requireNonNull(sourceAccountSettings);
    Objects.requireNonNull(preparePacket);
    Objects.requireNonNull(e);

    InterledgerRejectPacket rejectPacket = getInterledgerRejectPacket(sourceAccountSettings, preparePacket, e);
    publish(sourceAccountSettings, preparePacket, rejectPacket);
    return rejectPacket;
  }

  private InterledgerRejectPacket getInterledgerRejectPacket(AccountSettings sourceAccountSettings, InterledgerPreparePacket preparePacket, Exception e) {
    if (InterledgerProtocolException.class.isAssignableFrom(e.getClass())) {
      final InterledgerRejectPacket rejectPacket = ((InterledgerProtocolException) e).getInterledgerRejectPacket();
      logger.warn(
        "[OPERATOR: `{}`]: Rejecting PREPARE Packet. sourceAccountId={} preparePacket={} rejectPacket={} error={}",
        connectorSettingsSupplier.get().operatorAddress(),
        sourceAccountSettings.accountId(),
        preparePacket,
        rejectPacket,
        e.getMessage()
      );
      return rejectPacket;
    } else if (ArithmeticException.class.isAssignableFrom(e.getClass())) {
      logger.error(e.getMessage(), e);
      return this.packetRejector.reject(
        LinkId.of(sourceAccountSettings.accountId().value()),
        preparePacket,
        InterledgerErrorCode.F03_INVALID_AMOUNT,
        e.getMessage()
      );
    } else {
      logger.error(e.getMessage(), e);
      return this.packetRejector.reject(
        LinkId.of(sourceAccountSettings.accountId().value()),
        preparePacket,
        InterledgerErrorCode.T00_INTERNAL_ERROR,
        "Internal Error"
      );
    }
  }

  private void publish(AccountSettings sourceAccountSettings,
                                          InterledgerPreparePacket preparePacket,
                                          InterledgerRejectPacket rejectPacket) {
    packetEventPublisher.publishRejectionByConnector(sourceAccountSettings, preparePacket, rejectPacket);
  }

}
