# Uses a single BLAST endpoint and an additional Loopback endpoint for simple dev purposes.
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
logging:
  level:
    ROOT: INFO
    com.sappenin: INFO
    org.interledger: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    #org.springframework.web.socket: ERROR
    org.hibernate.SQL: INFO
    #org.hibernate.type.descriptor.sql.BasicBinder: INFO
server:
  port: 9000
  http2:
    enabled: true
  jetty:
    accesslog:
      enabled: true
      filename: /tmp/java-ilp-connector.log
      extended-format: true
      log-cookies: true
      log-server: true
      log-latency: true
      time-zone: MST
    max-http-post-size: 32767
#management:
#  endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    refresh:
#      enabled: true

spring:
  profiles:
    # see https://stackoverflow.com/questions/37700352
    active: ${spring.profiles.active}
  output:
    ansi:
      enabled: ALWAYS
  http:
    log-request-details: true
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  # Database Settings
  datasource:
    #url: jdbc:h2:mem:ilpv4-connector;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # Stores H2 to a file for persistence across server restarts
    url: jdbc:h2:/tmp/ilpv4-connector.bin;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      create_empty_composites:
        enabled: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true

###
#   H2 Settings
###
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false

redis:
  #host: localhost
  #port: 6379
  #password: shh

ilpv4:
  connector:
    # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
    adminPassword: password
    keystore:
      gcpkms:
        enabled: false
        # If running locally, `GOOGLE_CLOUD_PROJECT` must be defined as an environment variable with the correct GCP
        # project id
        locationId: global
      jks:
        enabled: true
        filename: crypto/crypto.p12
        # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
        password: password
        secret0_alias: secret0
        # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
        secret0_password: password
    defaultJwtTokenIssuer: https://connie.example.com
    enabledProtocols:
      blastEnabled: true
      pingProtocolEnabled: true
      peerConfigEnabled: true
      peerRoutingEnabled: true
    ## ILP address of the connector.
    ## This property can be omitted if an account with relation=parent is configured under accounts.
    nodeIlpAddress: test.connie
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # A simulated routing secret, which is a seed used for generating routing table auth values.
      # Represents the plaintext value of `shh`, encrypted.
      routingSecret: enc:JKS:crypto.p12:secret0:1:aes_gcm:AAAADKZPmASojt1iayb2bPy4D-Toq7TGLTN95HzCQAeJtz0=
      # Static Routes
      staticRoutes:
        # ILP address prefix that this static route applies to. Configured routes take precedence over the same or
        # shorter prefixes that are local or published by peers. More specific prefixes will still take precedence.
        # NOTE: Prefixes should NOT include a trailing period.
        - targetPrefix: test.ilpv4-dev.alice
          # ID of the account that destinations matching `targetPrefix` should be forwarded to. Must be one of the
          # accounts in `accounts`.
          peerAccountId: alice