# A Connector running in `plugin-mode` operates a single plugin, does not routing or balance tracking, and requires a
# parent ILSP that all traffic will be forwarded to.
logging:
  level:
    ROOT: INFO
    com.sappenin: TRACE
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web.socket: INFO
server:
  #port: 8080
  http2:
    enabled: true
  jetty:
    max-http-post-size: 32767 # Max per ILP ASN.1
spring:
  profiles:
    active: ${spring.profiles.active}
  output:
    ansi:
      enabled: ALWAYS
  http:
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      #max-file-size: 2KB
      #max-request-size: 2KB
  # Database Settings
#  datasource:
#    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

###
#   H2 Settings
###
#h2:
#  console:
#    enabled: true
#    path: /console
#    settings:
#      trace: false
#      web-allow-others: false
# Configuration for a Mini-Connector. Uncomment any value to enable a particular setting.
ilpv4:
  connector:
    blast.enabled: true
    btp.enabled: false
    enabledProtocols:
      pingProtocolEnabled: true
      echoProtocolEnabled: true
    ## ILP address of the connector.
    ## This property can be omitted if an account with relation=parent is configured under accounts.
    nodeIlpAddress: test.connie
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # Seed used for generating routing table auth values.
      routingSecret: DocIHaveToTellYouSomethingAboutY
    accounts:
      - id: test.alice
        description: Blast peer plugin
        # The default relationship-type that this connector should view an account as.
        relationship: PEER
        # Type of the Plugin that should be used for this account.
        pluginType: BlastPlugin
        # Whether we should broadcast routes to this peer. Defaults to false for relation=child and true otherwise.
        sendRoutes: false
        # Whether we should receive and process route broadcasts from this peer. Defaults to false for relation=child and true otherwise.
        receiveRoutes: false
        customSettings:
          blast.incoming.secret: 12345678912345678912345678912345
          blast.outgoing.secret: 12345678912345678912345678912345
          blast.outgoing.token_expiry: PT2M # See Duration.java for structure.
          blast.outgoing.url: http://localhost:8080/ilp

