# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
logging:
  level:
    ROOT: INFO
    com.sappenin: INFO
    org.interledger: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    com.auth0: ERROR
    org.springframework.web.socket: ERROR
server:
  port: 8080
  http2:
    enabled: true
  jetty:
    max-http-post-size: 32767
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    refresh:
#      enabled: true

spring:
  profiles:
    # see https://stackoverflow.com/questions/37700352
    active: ${spring.profiles.active}
  output:
    ansi:
      enabled: ALWAYS
  http:
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  # Database Settings
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false

ilpv4:
  connector:
    jwtTokenIssuer: https://alice.example.com
    enabledProtocols:
      blastEnabled: true
      pingProtocolEnabled: true
      peerConfigEnabled: true
      peerRoutingEnabled: true
    ## ILP address of the connector.
    ## This property can be omitted if an account with relation=parent is configured under accounts.
    nodeIlpAddress: test.alice
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # Seed used for generating routing table auth values.
      routingSecret: DocIHaveToTellYouSomethingAboutY
      # Static Routes
      staticRoutes:
        # ILP address prefix that this static route applies to. Configured routes take precedence over the same or
        # shorter prefixes that are local or published by peers. More specific prefixes will still take precedence.
        # NOTE: Prefixes should NOT include a trailing period.
        - targetPrefix: test.spsp.receiver
          # ID of the account that destinations matching `targetPrefix` should be forwarded to. Must be one of the
          # accounts in `accounts`.
          peerAccountId: receiver
    accounts:
      - id: sender
        description: The SPSP sender Account.
        # The default relationship-type that this connector should view an account as.
        relationship: CHILD
        # Type of the Link that should be used for this account.
        linkType: BlastLink
        assetCode: XRP
        assetScale: 9
        # Whether we should broadcast routes to this peer. Defaults to false for relation=child and true otherwise.
        sendRoutes: false
        # Whether we should receive and process route broadcasts from this peer. Defaults to false for relation=child and true otherwise.
        receiveRoutes: false
        maximumPacketAmount: 10
        customSettings:
          # Incoming
          blast.incoming.auth_type: SIMPLE
          blast.incoming.token_issuer: https://sender.example.com # The JWT issuer of the incoming token.
          blast.incoming.account_id: sender # The accountId held at this connector.
          blast.incoming.account_secret: somesecrettoken
          blast.incoming.token_expiry: PT2M # See Duration.java for structure.
          # Outgoing
          blast.outgoing.auth_type: simple
          blast.outgoing.token_issuer: https://alice.example.com # The JWT issuer of the outgoing token.
          blast.outgoing.account_id: sender # The accountId held at the remote server.
          blast.outgoing.account_secret: somesecrettoken
          blast.outgoing.token_expiry: PT2M # See Duration.java for structure.
          blast.outgoing.url: http://localhost:3000/ilp
      - id: receiver
        description: The SPSP receiver Account.
        # The default relationship-type that this connector should view an account as.
        relationship: PEER
        # Type of the Link that should be used for this account.
        linkType: BlastLink
        assetCode: XRP
        assetScale: 9
        # Whether we should broadcast routes to this peer. Defaults to false for relation=child and true otherwise.
        sendRoutes: true
        # Whether we should receive and process route broadcasts from this peer. Defaults to false for relation=child and true otherwise.
        receiveRoutes: true
        maximumPacketAmount: 100
        customSettings:
          # Incoming
          blast.incoming.auth_type: SIMPLE
          blast.incoming.token_issuer: https://example.com # Unused. Receiver only responds on outgoing
          blast.incoming.account_id: receiver # Unused. Receiver only responds on outgoing
          blast.incoming.account_secret: na # Unused. Receiver only responds on outgoing
          #blast.incoming.token_expiry: PT2M # Unused. Receiver only responds on outgoing
          # Outgoing
          blast.outgoing.auth_type: SIMPLE
          blast.outgoing.token_issuer: https://alice.example.com # Unused due to SIMPLE.
          blast.outgoing.account_id: receiver # The accountId held at the remote server.
          blast.outgoing.account_secret: somesecrettoken
          blast.outgoing.token_expiry: PT2M # 2 Mins
          blast.outgoing.url: http://localhost:3000/ilp # The SPSP receiver