# A custom properties file that can be used in the CI system.
logging:
  level:
    ROOT: DEBUG
server:
  http2:
    enabled: true
  jetty:
    max-http-post-size: 32767 # Max per ILP ASN.1
spring:
  output:
    ansi:
      enabled: ALWAYS
  http:
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB

  # Database Settings
  #datasource:
    #url: jdbc:postgresql://localhost:5432/connector
    #platform: postgresql
    #username: sa
    #password:
    #driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
        create_empty_composites:
          enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    session:
      persistent: false # Whether to persist session data between restarts.
      timeout: 0 # Session timeout. If a duration suffix is not specified, seconds will be used.
      tracking-modes: SSL # Session tracking modes.
  session:
    store-type: NONE

ilpv4:
  connector:
    btp.enabled: false
    enabledProtocols:
      blastEnabled: true
      pingProtocolEnabled: true
      peerConfigEnabled: true
      peerRoutingEnabled: true
    ## ILP address of the connector.
    ## This property can be omitted if an account with relation=parent is configured under accounts.
    nodeIlpAddress: test1.connie
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # A simulated routing secret, which is a seed used for generating routing table auth values.
      # Represents the plaintext value of `shh`, encrypted.
      routingSecret: enc:JKS:crypto.p12:secret0:1:aes_gcm:AAAADKZPmASojt1iayb2bPy4D-Toq7TGLTN95HzCQAeJtz0=