spring:
  # Database Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/connector
    platform: postgresql
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  liquibase:
    enabled: false
