# Uses a single BLAST endpoint and an additional Loopback endpoint for simple dev purposes.
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
logging:
  level:
    ROOT: INFO
    com: INFO
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO

server:
  port: 9000
  http2:
    enabled: true
  jetty:
#    accesslog:
#      enabled: true
#      filename: /tmp/java-ilp-connector.log
#      extended-format: true
#      log-cookies: true
#      log-server: true
#      log-latency: true
#      time-zone: MST
    max-http-post-size: 32767

spring:
  output:
    ansi:
      enabled: ALWAYS
  http:
    log-request-details: false
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  # Database Settings
  datasource:
    #url: jdbc:h2:mem:connector-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # Stores H2 to a file for persistence across server restarts
    url: jdbc:h2:/tmp/connector-db.bin;DB_CLOSE_ON_EXIT=FALSE
    #platform: h2
    #username: sa
    #password:
    #driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      #ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        generate_statistics: false

###
#   H2 Settings
###
h2:
  console:
    enabled: false
    path: /console
    settings:
      trace: false
      web-allow-others: false

redis:
  #host: localhost
  #port: 6379
  #password: shh

  interledger.connector.ilpOverHttp.connectionDefaults.maxIdleConnections


interledger:
  connector:
    # Connector-wide defaults for ilp-over-http Links
    ilpOverHttp:
      connectionDefaults: # Must not be commented out in order for Spring Props to work.
        # Applied when connecting a TCP socket to the target host. A value of 0 means no timeout, otherwise values must
        # be between 1 and {@link Integer#MAX_VALUE} when converted to milliseconds.  If unspecified, defaults to 10.
        #connectTimeoutMillis: 2000
        # This is applied to both the TCP socket and for individual read IO operations. A value of 0 means no timeout,
        # otherwise values must be between 1 and {@link Integer#MAX_VALUE} when converted to milliseconds.  If
        # unspecified, defaults to 10.
        #readTimeoutMillis: 1000
        # Applied to individual write IO operations. A value of 0 means no timeout, otherwise values must be between 1
        # and {@link Integer#MAX_VALUE} when converted to milliseconds. If unspecified, defaults to 10.
        #writeTimeoutMillis: 1000
        maxIdleConnections: 10
        #keepAliveMinutes: 1

    # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
    adminPassword: password
    keystore:
      gcpkms:
        enabled: false
        # If running locally, `GOOGLE_CLOUD_PROJECT` must be defined as an environment variable with the correct GCP
        # project id
        locationId: global
      jks:
        enabled: true
        filename: crypto/crypto.p12
        # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
        password: password
        secret0_alias: secret0
        # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
        secret0_password: password
    defaultJwtTokenIssuer: https://connie.example.com
    enabledProtocols:
      blastEnabled: true
      pingProtocolEnabled: true
      peerConfigEnabled: true
      peerRoutingEnabled: true
    ## ILP address of the connector.
    ## This property can be omitted if an account with relation=parent is configured under accounts.
    nodeIlpAddress: test.connie
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # A simulated routing secret, which is a seed used for generating routing table auth values.
      # Represents the plaintext value of `shh`, encrypted.
      routingSecret: enc:JKS:crypto.p12:secret0:1:aes_gcm:AAAADKZPmASojt1iayb2bPy4D-Toq7TGLTN95HzCQAeJtz0=
      # Static Routes
      staticRoutes:
        # ILP address prefix that this static route applies to. Configured routes take precedence over the same or
        # shorter prefixes that are local or published by peers. More specific prefixes will still take precedence.
        # NOTE: Prefixes should NOT include a trailing period.
        - targetPrefix: test.connie.alice
          # ID of the account that destinations matching `targetPrefix` should be forwarded to. Must be one of the
          # accounts in `accounts`.
          peerAccountId: alice
