# Used for pure development purposes. All accounts are simulated using the Loopback Link.
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
interledger:
  connector:
    keystore:
      primary: gcpkms
      gcpkms:
        enabled: true
        locationId: global
        keyringId: connector

## uncomment to provide gcp service account as a base64-encoded value
#spring:
#  cloud:
#    gcp:
#      credentials:
#        encoded-key: your-base64-encoded-service-account-key-json