spring:
  profiles:
    include: dev

interledger:
  connector:
    nodeIlpAddress: test.connie
    defaultJwtTokenIssuer: https://connie.example.com

    # Global Routing Settings for this connector.
    globalRoutingSettings:
      staticRoutes:
        # ILP address prefix that this static route applies to. Configured routes take precedence over the same or
        # shorter prefixes that are local or published by peers. More specific prefixes will still take precedence.
        # NOTE: Prefixes should NOT include a trailing period.
        - targetPrefix: test.connie.alice
          # ID of the account that destinations matching `targetPrefix` should be forwarded to. Must be one of the
          # accounts in `accounts`.
          peerAccountId: alice
