# Wallet Mode enables a Connector to do more than just packet switching. It also enables the Connector to support
#  SPSP, both via a REST endpoint for STREAM connection generation as well as STREAM receiver termination.
spring:
  banner:
    location: classpath:banner-packet-switch-mode.txt

interledger:
  connector:
    spsp:
      # Empty by default.
      urlPath:
    enabledFeatures:
      # Connectors in packet-switch mode generally don't terminate packets, but instead usually forward them.
      localSpspFulfillmentEnabled: false
    enabledProtocols:
      # Connectors in packet-switch mode generally don't terminate packets, but instead usually forward them.
      spspEnabled: false
