###
#   H2 Settings
###
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false

spring:
  # Database Settings
  datasource:
    url: jdbc:h2:/tmp/connector-db.bin;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  liquibase:
    enabled: false

---
## default h2 profile makes a persistent database. this additional profile overrides it to in-memory
spring:
  profiles: h2-in-memory
  datasource:
    url: jdbc:h2:mem:connector-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
